openapi: 3.0.1
info:
  title: Solution Data API
  description: >-
    Solutions Data API is the single entrypoint to access aggregated and
    processed data from Swarm Perception Boxes®.
  version: 0.8.0
  license:
    name: Commercial License
servers:
  - url: 'https://swarm-data-center.azurewebsites.net/v1'
    description: Sandbox Server (test data)
paths:
  '/parkingdata/spaces/{spaceUUID}':
    get:
      tags:
        - Parking
      summary: Get the last state of a given parking space UUID.
      description: >-
        Parking space UUID can be obtained from the Swarm Control Center or its
        API
      parameters:
        - name: spaceUUID
          in: path
          description: UUID of the parking space
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  node:
                    $ref: >-
                      https://raw.githubusercontent.com/hal9000-swarm/swarm-event-schema/master/swarm-event-schema.json#/definitions/node
                  event:
                    $ref: >-
                      https://raw.githubusercontent.com/hal9000-swarm/swarm-event-schema/master/swarm-event-schema.json#/definitions/regionOfInterestEvent
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/trafficdata/crossinglines/{lineUUID}':
    get:
      tags:
        - Traffic Monitoring
      summary: Retrieves information about objects that crossed a counting line.
      description: >-
        Line UUID can be retrieved from the Swarm Control Center or its API.
        <br/> As default returns data for the last hour. This can be adjusted by
        setting query parameters.
      parameters:
        - name: lineUUID
          in: path
          description: UUID of the counting line
          required: true
          schema:
            type: string
            format: uuid
        - name: from
          in: query
          description: Start date-time of the time-window
          schema:
            type: string
            format: date-time
        - name: to
          in: query
          description: End date-time of the time-window
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  node:
                    $ref: >-
                      https://raw.githubusercontent.com/hal9000-swarm/swarm-event-schema/master/swarm-event-schema.json#/definitions/node
                  event:
                    $ref: >-
                      https://raw.githubusercontent.com/hal9000-swarm/swarm-event-schema/master/swarm-event-schema.json#/definitions/crossingLineEvent
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /trafficdata/flows:
    get:
      tags:
        - Traffic Monitoring
      summary: Get traffic flows from Entry Zone to Exit Zone for a given time window
      description: >-
        Entry-zone and exit-zone UUID can be obtained from the Swarm Control
        Center.  <br/> As default returns data for the last hour. This can be
        adjusted by setting query parameters.
      parameters:
        - name: entryZone
          in: query
          description: UUID of the entry zone
          schema:
            type: string
            format: uuid
        - name: exitZone
          in: query
          description: UUID of the exit zone
          schema:
            type: string
            format: uuid
        - name: from
          in: query
          description: Start date-time of the time-window
          schema:
            type: string
            format: date-time
        - name: to
          in: query
          description: End date-time of the time-window
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  node:
                    $ref: >-
                      https://raw.githubusercontent.com/hal9000-swarm/swarm-event-schema/master/trafficMonitoring/traffic-monitoring-event-schema.json#/definitions/node
                  event:
                    $ref: >-
                      https://raw.githubusercontent.com/hal9000-swarm/swarm-event-schema/master/trafficMonitoring/traffic-monitoring-event-schema.json#/definitions/trafficEvent
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string
